package StockObjects;


/**
* StockObjects/Quote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
*/

public final class Quote implements org.omg.CORBA.portable.IDLEntity
{
  public String symbol = null;
  public int at_time = (int)0;
  public double price = (double)0;
  public int volume = (int)0;

  public Quote ()
  {
  } // ctor

  public Quote (String _symbol, int _at_time, double _price, int _volume)
  {
    symbol = _symbol;
    at_time = _at_time;
    price = _price;
    volume = _volume;
  } // ctor

} // class Quote
