package StockObjects;


/**
* StockObjects/Stock.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
*/

public interface Stock extends StockOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Stock
