package StockObjects;


/**
* StockObjects/StockFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
*/

public interface StockFactoryOperations
{
  StockObjects.Stock create_stock (String symbol, String description);
} // interface StockFactoryOperations
