package StockObjects;


/**
* StockObjects/StockFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
*/

public interface StockFactory extends StockFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface StockFactory
