package StockObjects;


/**
* StockObjects/StockOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stock.idl
*/

public interface StockOperations
{

  // Returns the current stock quote.
  StockObjects.Quote get_quote () throws StockObjects.Unknown;

  // Sets the current stock quote.
  void set_quote (StockObjects.Quote stock_quote);

  // e.g. company name.
  String description ();
} // interface StockOperations
